version: '3'

volumes:
  phpfpm-socket:

services:
  web:
    build: ./nginx
    container_name: nginx-sock
    hostname: project_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./project:/var/www/html
      - ./logs:/var/log/nginx
      - phpfpm-socket:/var/run

    links:
      - php
  php:
    build: ./php
    container_name: php7.3-sock
    hostname: project_php
    volumes:
      - ./project:/var/www/html
      - ./php/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - phpfpm-socket:/var/run